<a href="https://colab.research.google.com/github/widura26/recap-automation/blob/main/recap_automation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Summary

Source : [link text](https://docs.google.com/spreadsheets/d/1Ibki18gicAFziEx1urTrvDv_KkzrkMMnRrbwqNYpOkw/edit?usp=sharing)

 List BOM
* Elektrik + Pre Series ✅ ✅
* De-Scoping ✅
* Interior ✅ ✅
* TMS ✅
* CKD VVVF ✅
* CKD Pantograph ✅
* CKD SIV ✅
* Elektrik ✅ ✅
* Komponen Utama ✅ ✅
* Sistem Mekanik ✅ ✅
* Raw Material Interior ✅
* Bogie KIT ✅
* Raw Material Bogie ✅
* Realisasi Raw Material ✅
* Carbody
* Fastening Mekanik
* Fastening Bogie
* Fastening Interior
* Crashwrothiness
* Welding
* Welding Bogie
* Consumable Tools ✅
* Consumable Series
* Welding WS BWI
* Jig Tools 6TS Pelokalan
* Jig Tool
* Tools ✅
* Tools & Consumable Tools Perbaikan ✅ ✅
* Consumable Pre Series ✅✅

---

Required data
*   Kode Material
*   Material (Nama material)
*   Spesifikasi
*   Qty / TS

In [1]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 33.4 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.6

In [2]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
import pandas as pd
import re
import plotly.express as px
from rapidfuzz import fuzz
from difflib import SequenceMatcher
import regex as re

# Grabbing data (important)

In [37]:
# creds, _ = default()
# client = gspread.authorize(creds)

# nama_file_sheets = "bom_dataset"
# spreadsheet = client.open(nama_file_sheets)


# # ============================================================
# # 2. DAFTAR SHEET TARGET
# # ============================================================

# DAFTAR_SHEET_TARGET = [
#     "Elektrik + Pre Series", "De-Scoping", "Interior", "TMS", "CKD VVVF",
#     "CKD Pantograph", "CKD SIV", "Elektrik", "Komponen Utama", "Sistem Mekanik",
#     "Raw Material Interior", "Bogie KIT", "Raw Material Bogie", "Realisasi Raw Material",
#     "Carbody", "Fastening Mekanik", "Fastening Bogie", "Fastening Interior",
#     "Crashwrothiness", "Welding", "Welding Bogie", "Consumable Tools",
#     "Consumable Series", "Welding WS BWI", "Jig Tools 6TS Pelokalan", "jig Tool",
#     "Tools", "Tools & Consumable Tools Perbaikan", "Consumable Pre Series"
# ]

# semua_tab = spreadsheet.worksheets()
# sheet_names_aktual = [sheet.title for sheet in semua_tab]

# # ============================================================
# # 3. NORMALISASI
# # ============================================================

# def normalize_text(text):
#     """Normalisasi teks untuk pencocokan header."""
#     if text is None:
#         return ""

#     text = str(text).strip().lower()
#     text = re.sub(r"[^a-z0-9]+", " ", text)
#     text = re.sub(r"\s+", " ", text)

#     return text.strip()


# def normalize_compact(text):
#     """Contoh: 'Kode Material' -> 'kodematerial'."""
#     return re.sub(r"[^a-z0-9]", "", normalize_text(text))


# def tokenize(text):
#     normalized = normalize_text(text)
#     return set(normalized.split()) if normalized else set()


# # ============================================================
# # 4. CARI SHEET AKTUAL
# # ============================================================

# def cari_sheet_aktual(nama_target):
#     target = normalize_text(nama_target)
#     target_compact = normalize_compact(nama_target)

#     # Exact normalized
#     for actual in sheet_names_aktual:
#         if normalize_text(actual) == target:
#             return actual

#     # Exact compact
#     for actual in sheet_names_aktual:
#         if normalize_compact(actual) == target_compact:
#             return actual

#     return None


# target_sheets_matched = []

# for nama_target in DAFTAR_SHEET_TARGET:
#     matched = cari_sheet_aktual(nama_target)
#     if matched and matched not in target_sheets_matched:
#         target_sheets_matched.append(matched)


# print(
#     f"[INFO] Memetakan {len(target_sheets_matched)} dari "
#     f"{len(DAFTAR_SHEET_TARGET)} target sheet.\n"
# )


# # ============================================================
# # 5. MASTER HEADER / ALIAS
# # ============================================================

# KATA_KUNCI = {
#     "kode": [
#         "kode material",
#         "material code",
#         "material kode",
#         "item code",
#         "part number",
#         "part no",
#         "part no.",
#         "kode material asli"
#     ],
#     "kode_delete": [
#         "kode material delete",
#         "material delete code",
#         "delete material code"
#     ],
#     "stock_total": [
#         "stock total",
#         "total stock",
#         "stock total (series)",
#     ],
#     "kode_stock": [
#         "kode material stock",
#         "kode material stock 1",
#         "kode material stock 2",
#         "kode material stock 3",
#         "kode material stock 4",
#         "kode material stock 5",
#         "kode material stok",
#         "kode material stok 1",
#         "kode material stok 2",
#         "kode material stok 3",
#         "kode material stok 4",
#         "kode material stok 5",
#         "material stock code",
#         "stock material code",
#         "stock code",
#         "kode stock",
#         "kode stok"
#     ],
#     "nama": [
#         "material / komponen",
#         "material/komponen",
#         "deskripsi material",
#     ],
#     "spek": [
#         "spesifikasi",
#         "specification",
#         "spec",
#         "detail spesifikasi",
#         "SPESIFIKASI"
#     ],
#     "qty": [
#         "qty / ts (series)",
#         "qty/ts (series)",
#         "qty ts series",
#     ],
#     "uom": [
#         "uom/car",
#         "uom / car",
#         "uom",
#         "unit",
#         "satuan",
#         "uom/bogie"
#     ],
#     "qty_allowance": [
#         "qty total (series)",
#         "qty total series",
#         "Qty Total (Series) + Allowance"
#     ],
#     "qty_pr_total": [
#         "qty pr total",
#         "total pr"
#     ]
# }

# ALIAS_PENDEK = {
#     "kode": {"kode"},
#     "spek": {"spec"},
#     "uom": {"uom", "unit", "satuan"},
# }


# # ============================================================
# # 6. EXACT MATCHING HEADER BERDASARKAN KATA_KUNCI
# # ============================================================

# def _header_parts(text):
#     """
#     Mengambil bagian-bagian header yang berasal dari multi-row header.

#     gabungkan_header() menggunakan pemisah ``||`` agar parent header seperti
#     "Pengadaan" dan "Scope INKA" tidak dianggap sebagai bagian dari nama
#     field. Setiap bagian kemudian bisa dicocokkan secara exact terhadap
#     KATA_KUNCI.
#     """
#     if text is None:
#         return []

#     raw_parts = str(text).split("||")
#     return [part.strip() for part in raw_parts if part.strip()]


# def similarity_header(text, keyword, field=None):
#     """
#     Exact matching terhadap KATA_KUNCI dengan dukungan multi-row header.

#     Untuk header biasa:
#         "Total PR" -> cocok dengan "total pr".

#     Untuk multi-row header:
#         "Pengadaan || Scope INKA || Total PR" -> tetap cocok dengan
#         keyword "total pr" karena pencocokan dilakukan pada setiap bagian
#         header, bukan pada gabungan seluruh parent header.

#     Tidak menggunakan fuzzy matching, substring, token subset, atau
#     SequenceMatcher.
#     """
#     if not normalize_text(keyword):
#         return 0

#     key_norm = normalize_text(keyword)
#     key_compact = normalize_compact(key_norm)

#     for part in _header_parts(text):
#         text_norm = normalize_text(part)

#         if not text_norm:
#             continue

#         # Guard untuk memisahkan Kode Material dan Kode Material Delete.
#         if field == "kode" and "delete" in text_norm.split():
#             continue

#         # Guard tambahan untuk mencegah Qty Total (Pre Series) tertukar
#         # dengan Qty Total (Series).
#         if field == "qty_allowance" and "pre" in text_norm.split():
#             continue

#         # Exact setelah normalisasi teks.
#         if text_norm == key_norm:
#             return 100

#         # Exact setelah spasi dan tanda baca dihilangkan.
#         # Contoh: "Material/Komponen" == "Material / Komponen".
#         text_compact = normalize_compact(text_norm)
#         if text_compact == key_compact:
#             return 98

#     return 0


# # Threshold per field
# # Tetap dipertahankan untuk kompatibilitas; matching sekarang hanya menghasilkan 0, 98, atau 100.
# THRESHOLD_FIELD = {
#     "kode": 78,
#     "kode_delete": 78,
#     "stock_total": 70,
#     "kode_stock": 78,
#     "nama": 72,
#     "spek": 72,
#     "qty": 72,
#     "uom": 75,
#     "qty_allowance": 80,  # Ditingkatkan sedikit untuk mencegah false positive pada 'Pre Series'
#     "qty_pr_total": 70,
# }


# # ============================================================
# # 7. GABUNGKAN MULTI-ROW HEADER
# # ============================================================

# def gabungkan_header(data, start_row, jumlah_baris):
#     end_row = min(start_row + jumlah_baris, len(data))
#     if start_row >= end_row:
#         return []

#     max_col = max(len(data[row_idx]) for row_idx in range(start_row, end_row))
#     hasil = []

#     for col_idx in range(max_col):
#         values = []
#         for row_idx in range(start_row, end_row):
#             if col_idx >= len(data[row_idx]):
#                 continue
#             value = str(data[row_idx][col_idx]).strip()
#             if not value:
#                 continue
#             if value not in values:
#                 values.append(value)
#         # Simpan setiap level header secara terpisah. Ini penting agar
#         # "Pengadaan || Scope INKA || Total PR" tetap bisa menemukan
#         # keyword exact "Total PR" tanpa harus memasukkan parent header
#         # ke dalam KATA_KUNCI.
#         hasil.append(" || ".join(values))

#     return hasil


# # ============================================================
# # 8. MATCHING FIELD KE KOLOM SECARA GLOBAL
# # ============================================================

# def cari_mapping_header(header_columns):
#     kandidat = []

#     for col_idx, header_text in enumerate(header_columns):
#         if not normalize_text(header_text):
#             continue

#         for field, keywords in KATA_KUNCI.items():
#             best_score = 0
#             best_keyword = None

#             for keyword in keywords:
#                 score = similarity_header(header_text, keyword, field=field)
#                 if score > best_score:
#                     best_score = score
#                     best_keyword = keyword

#             threshold = THRESHOLD_FIELD[field]

#             if best_score >= threshold:
#                 kandidat.append({
#                     "field": field,
#                     "col_idx": col_idx,
#                     "score": best_score,
#                     "keyword": best_keyword,
#                     "header": header_text
#                 })

#     kandidat.sort(key=lambda x: x["score"], reverse=True)

#     mapping = {
#         "kode": None, "kode_delete": None, "stock_total": None,
#         "kode_stock": None, "nama": None, "spek": None,
#         "qty": None, "uom": None, "qty_allowance": None, "qty_pr_total": None
#     }

#     field_scores = {field: 0 for field in mapping}
#     kolom_terpakai = set()

#     for item in kandidat:
#         field = item["field"]
#         col_idx = item["col_idx"]

#         if mapping[field] is not None:
#             continue
#         if col_idx in kolom_terpakai:
#             continue

#         mapping[field] = col_idx
#         field_scores[field] = item["score"]
#         kolom_terpakai.add(col_idx)

#     return mapping, field_scores, kandidat


# # ============================================================
# # 9. CARI HEADER TERBAIK
# # ============================================================

# def deteksi_header(data, max_scan=100, max_header_rows=4):
#     kandidat_header = []
#     jumlah_baris_scan = min(max_scan, len(data))

#     for start_row in range(jumlah_baris_scan):
#         for jumlah_baris in range(1, max_header_rows + 1):
#             end_row_exclusive = start_row + jumlah_baris
#             if end_row_exclusive > len(data):
#                 continue

#             header_columns = gabungkan_header(data, start_row, jumlah_baris)
#             mapping, field_scores, kandidat_field = cari_mapping_header(header_columns)

#             jumlah_field = sum(1 for value in mapping.values() if value is not None)
#             if jumlah_field == 0:
#                 continue

#             first_row_mapping, _, _ = cari_mapping_header(data[start_row])
#             jumlah_field_first_row = sum(1 for value in first_row_mapping.values() if value is not None)

#             total_score = sum(field_scores.values())
#             bonus_identitas = 0

#             if mapping["kode"] is not None:
#                 bonus_identitas += 25
#             if mapping["nama"] is not None:
#                 bonus_identitas += 35

#             strong_matches = sum(1 for value in field_scores.values() if value >= 95)
#             total_score += bonus_identitas + (strong_matches * 5)

#             if mapping["kode"] is None and mapping["nama"] is None:
#                 continue

#             kandidat_header.append({
#                 "row_idx": start_row,
#                 "end_row_idx": end_row_exclusive - 1,
#                 "jumlah_baris": jumlah_baris,
#                 "mapping": mapping,
#                 "field_scores": field_scores,
#                 "score": total_score,
#                 "jumlah_field": jumlah_field,
#                 "jumlah_field_first_row": jumlah_field_first_row,
#                 "header_columns": header_columns,
#                 "kandidat_field": kandidat_field
#             })

#     if not kandidat_header:
#         return None

#     kandidat_header.sort(
#         key=lambda x: (
#             x["jumlah_field"],
#             x["jumlah_field_first_row"],
#             x["score"],
#             -x["jumlah_baris"]
#         ),
#         reverse=True
#     )

#     return kandidat_header[0]


# # ============================================================
# # 10. DEBUG HEADER
# # ============================================================

# def tampilkan_debug_header(hasil_header):
#     print(f"  Header range: Row {hasil_header['row_idx'] + 1} - {hasil_header['end_row_idx'] + 1}")
#     print(f"  Jumlah baris header: {hasil_header['jumlah_baris']}")
#     print(f"  Jumlah header terdeteksi: {hasil_header['jumlah_field']}")
#     print(f"  Mapping: {hasil_header['mapping']}")
#     print("  Detail mapping:")

#     for field, col_idx in hasil_header["mapping"].items():
#         if col_idx is None:
#             print(f"    - {field}: TIDAK TERDETEKSI")
#             continue

#         score = hasil_header["field_scores"].get(field, 0)
#         header_text = hasil_header["header_columns"][col_idx]
#         print(f"    - {field}: kolom {col_idx + 1}, score={score}, header='{header_text}'")


# # ============================================================
# # 11. PARSE ANGKA
# # ============================================================

# def parse_number(value):
#     if value is None:
#         return 0.0

#     text = str(value).strip()
#     if not text:
#         return 0.0

#     text_upper = text.upper()
#     invalid_values = [
#         "N/A", "-", "#N/A", "#VALUE!", "#REF!", "#DIV/0!", "#NAME?", "#REF"
#     ]

#     if text_upper in invalid_values:
#         return 0.0

#     text = text.replace(",", ".")
#     match = re.search(r"-?\d+(?:\.\d+)?", text)

#     if not match:
#         return 0.0

#     try:
#         return float(match.group(0))
#     except ValueError:
#         return 0.0


# # ============================================================
# # 12. HELPER AMBIL CELL
# # ============================================================

# def get_cell(row, col_idx, default=""):
#     if col_idx is None or col_idx < 0 or col_idx >= len(row):
#         return default
#     return str(row[col_idx]).strip()


# # ============================================================
# # 13. PROSES SEMUA SHEET
# # ============================================================

# rekap_data = []

# for target_name in target_sheets_matched:
#     sheet = spreadsheet.worksheet(target_name)
#     data_mentah = sheet.get_all_values()

#     if not data_mentah:
#         print(f"Sheet '{target_name}' -> [SKIP] Tidak ada data.")
#         continue

#     hasil_header = deteksi_header(data_mentah, max_scan=100, max_header_rows=5)

#     if hasil_header is None:
#         print(f"Sheet '{target_name}' -> [SKIP] Header tidak ditemukan.")
#         continue

#     mapping = hasil_header["mapping"]

#     print(f"\nSheet '{target_name}'")
#     tampilkan_debug_header(hasil_header)

#     if mapping["kode"] is None and mapping["nama"] is None:
#         print("  -> [SKIP] Tidak ada kolom Kode Material atau Material/Komponen.")
#         continue

#     data_start_idx = hasil_header["end_row_idx"] + 1
#     print(f"  Data mulai pada Row {data_start_idx + 1}")

#     baris_terproses = 0

#     for row in data_mentah[data_start_idx:]:
#         kode_material = get_cell(row, mapping["kode"])
#         kode_material_delete = get_cell(row, mapping["kode_delete"])
#         stock_total = parse_number(get_cell(row, mapping["stock_total"]))
#         kode_stock = get_cell(row, mapping["kode_stock"])
#         nama_material = get_cell(row, mapping["nama"])
#         spesifikasi = get_cell(row, mapping["spek"])
#         uom_car = get_cell(row, mapping["uom"])

#         valid_qty = parse_number(get_cell(row, mapping["qty"]))
#         valid_allowance = parse_number(get_cell(row, mapping["qty_allowance"]))
#         valid_pr_total = parse_number(get_cell(row, mapping["qty_pr_total"]))

#         kata_abaikan = {
#             "kode material", "kode", "total", "subtotal",
#             "header", "item code", "part number", "k o d e"
#         }

#         kode_lower = kode_material.lower().strip()

#         if not kode_material and not kode_material_delete:
#             continue
#         if kode_lower in kata_abaikan:
#             continue
#         if kode_material_delete.lower().strip() in kata_abaikan:
#             continue

#         rekap_data.append([
#             target_name,
#             kode_material,
#             kode_material_delete,
#             kode_stock,
#             stock_total,
#             nama_material,
#             spesifikasi,
#             valid_qty,
#             uom_car,
#             valid_allowance,
#             valid_pr_total
#         ])

#         baris_terproses += 1

#     print(f"  -> {baris_terproses} baris terambil.")


# # ============================================================
# # 14. DATAFRAME
# # ============================================================

# df_rekap = pd.DataFrame(
#     rekap_data,
#     columns=[
#         "Nama Sheet Sumber",
#         "Kode Material",
#         "Kode Material Delete",
#         "Kode Material Stock",
#         "Stock Total",
#         "Material / Komponen",
#         "Spesifikasi",
#         "Qty / TS (Series)",
#         "UoM/Car",
#         "Qty Total (Series) + Allowance",
#         "QTY PR TOTAL"
#     ]
# )


# # ============================================================
# # 15. RINGKASAN
# # ============================================================

# print("\n--- RINGKASAN HASIL PER SHEET ---")

# if not df_rekap.empty:
#     print(df_rekap.groupby("Nama Sheet Sumber").size())
# else:
#     print("Tidak ada data yang berhasil diambil.")


# # ============================================================
# # 16. TULIS KE GOOGLE SHEETS
# # ============================================================

# nama_tab_rekap = "REKAP_BOM_TOTAL (Berdasarkan Kode Material) 2"

# try:
#     sheet_rekap = spreadsheet.worksheet(nama_tab_rekap)
#     sheet_rekap.clear()
# except gspread.exceptions.WorksheetNotFound:
#     sheet_rekap = spreadsheet.add_worksheet(
#         title=nama_tab_rekap,
#         rows="8000",
#         cols="11"
#     )

# data_ke_sheets = (
#     [df_rekap.columns.values.tolist()]
#     + df_rekap.values.tolist()
# )

# sheet_rekap.update(data_ke_sheets)

# print(
#     f"\n[SUKSES] TOTAL {len(df_rekap)} baris data berhasil "
#     f"ditarik dan disimpan ke sheet '{nama_tab_rekap}'."
# )

[INFO] Memetakan 29 dari 29 target sheet.


Sheet 'Elektrik + Pre Series'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 385 baris terambil.

Sheet 'De-Scoping'
  Header range: Row 5 - 7
  Jumlah baris header: 3
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 37, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 36, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 38, score=100, header='Pengadaan || Scope INKA || Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 37, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series) || + Allowance'
    - qty_pr_total: kolom 45, score=100, header='Total PR'
  Data mulai pada Row 8
  -> 768 baris terambil.

Sheet 'Interior'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material/Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 435 baris terambil.

Sheet 'TMS'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 28 baris terambil.

Sheet 'CKD VVVF'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 185 baris terambil.

Sheet 'CKD Pantograph'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 394 baris terambil.

Sheet 'CKD SIV'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 160 baris terambil.

Sheet 'Elektrik'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 465 baris terambil.

Sheet 'Komponen Utama'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 179 baris terambil.

Sheet 'Sistem Mekanik'
  Header range: Row 5 - 6
  Jumlah baris header: 2
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 532 baris terambil.

Sheet 'Raw Material Interior'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='SPESIFIKASI'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 82 baris terambil.

Sheet 'Bogie KIT'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Bogie'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 44 baris terambil.

Sheet 'Raw Material Bogie'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 6, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 7, score=100, header='Kode Material Stock 1'
    - nama: kolom 13, score=100, header='Deskripsi Material'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 99 baris terambil.

Sheet 'Realisasi Raw Material'
  Header range: Row 4 - 5
  Jumlah baris header: 2
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 7, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material Asli'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 8, score=100, header='Kode Material Stock 2'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 6
  -> 123 baris terambil.

Sheet 'Carbody'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material/Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 268 baris terambil.

Sheet 'Fastening Mekanik'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=98, header='KodeMaterial'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='Total PR'
  Data mulai pada Row 7
  -> 984 baris terambil.

Sheet 'Fastening Bogie'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=98, header='KodeMaterial'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 123 baris terambil.

Sheet 'Fastening Interior'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=98, header='KodeMaterial'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 562 baris terambil.

Sheet 'Crashwrothiness'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 19 baris terambil.

Sheet 'Welding'
  Header range: Row 5 - 6
  Jumlah baris header: 2
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series) + Allowance'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 118 baris terambil.

Sheet 'Welding Bogie'
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 9
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': None, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: TIDAK TERDETEKSI
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 8 baris terambil.

Sheet 'Consumable Tools'
  Header range: Row 6 - 6
  Jumlah baris header: 1

In [212]:
creds, _ = default()
client = gspread.authorize(creds)

nama_file_sheets = "bom_dataset"
spreadsheet = client.open(nama_file_sheets)


# ============================================================
# 2. DAFTAR SHEET TARGET
# ============================================================

DAFTAR_SHEET_TARGET = [
    "Elektrik + Pre Series", "De-Scoping", "Interior", "TMS", "CKD VVVF",
    "CKD Pantograph", "CKD SIV", "Elektrik", "Komponen Utama", "Sistem Mekanik",
    "Raw Material Interior", "Bogie KIT", "Raw Material Bogie", "Realisasi Raw Material",
    "Carbody", "Fastening Mekanik", "Fastening Bogie", "Fastening Interior",
    "Crashwrothiness", "Welding", "Welding Bogie", "Consumable Tools",
    "Consumable Series", "Welding WS BWI", "Jig Tools 6TS Pelokalan", "jig Tool",
    "Tools", "Tools & Consumable Tools Perbaikan", "Consumable Pre Series"
]

semua_tab = spreadsheet.worksheets()
sheet_names_aktual = [sheet.title for sheet in semua_tab]

# ============================================================
# 3. NORMALISASI
# ============================================================

def normalize_text(text):
    """Normalisasi teks untuk pencocokan header."""
    if text is None:
        return ""

    text = str(text).strip().lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def normalize_compact(text):
    """Contoh: 'Kode Material' -> 'kodematerial'."""
    return re.sub(r"[^a-z0-9]", "", normalize_text(text))


def tokenize(text):
    normalized = normalize_text(text)
    return set(normalized.split()) if normalized else set()


# ============================================================
# 4. CARI SHEET AKTUAL
# ============================================================

def cari_sheet_aktual(nama_target):
    target = normalize_text(nama_target)
    target_compact = normalize_compact(nama_target)

    # Exact normalized
    for actual in sheet_names_aktual:
        if normalize_text(actual) == target:
            return actual

    # Exact compact
    for actual in sheet_names_aktual:
        if normalize_compact(actual) == target_compact:
            return actual

    return None


target_sheets_matched = []

for nama_target in DAFTAR_SHEET_TARGET:
    matched = cari_sheet_aktual(nama_target)
    if matched and matched not in target_sheets_matched:
        target_sheets_matched.append(matched)


print(
    f"[INFO] Memetakan {len(target_sheets_matched)} dari "
    f"{len(DAFTAR_SHEET_TARGET)} target sheet.\n"
)


# ============================================================
# 5. MASTER HEADER / ALIAS
# ============================================================

KATA_KUNCI = {
    "kode": [
        "kode material",
        "material code",
        "material kode",
        "item code",
        "part number",
        "part no",
        "part no.",
        "kode material asli"
    ],
    "kode_delete": [
        "kode material delete",
        "material delete code",
        "delete material code"
    ],
    "stock_total": [
        "stock total",
        "total stock",
        "stock total (series)",
    ],
    "kode_stock": [
        "kode material stock",
        "kode material stock 1",
        "kode material stock 2",
        "kode material stock 3",
        "kode material stock 4",
        "kode material stock 5",
        "kode material stok",
        "kode material stok 1",
        "kode material stok 2",
        "kode material stok 3",
        "kode material stok 4",
        "kode material stok 5",
        "material stock code",
        "stock material code",
        "stock code",
        "kode stock",
        "kode stok"
    ],
    "nama": [
        "material / komponen",
        "material/komponen",
        "deskripsi material",
    ],
    "spek": [
        "spesifikasi",
        "specification",
        "spec",
        "detail spesifikasi",
        "SPESIFIKASI"
    ],
    "qty": [
        "qty / ts (series)",
        "qty/ts (series)",
        "qty ts series",
    ],
    "uom": [
        "uom/car",
        "uom / car",
        "uom",
        "unit",
        "satuan",
        "uom/bogie"
    ],
    "qty_allowance": [
        "qty total (series)",
        "qty total series",
        "Qty Total (Series) + Allowance"
    ],
    "qty_pr_total": [
        "qty pr total",
        "total pr"
    ]
}

ALIAS_PENDEK = {
    "kode": {"kode"},
    "spek": {"spec"},
    "uom": {"uom", "unit", "satuan"},
}


# ============================================================
# 6. EXACT MATCHING HEADER BERDASARKAN KATA_KUNCI
# ============================================================

def _header_parts(text):
    """
    Mengambil bagian-bagian header yang berasal dari multi-row header.

    gabungkan_header() menggunakan pemisah ``||`` agar parent header seperti
    "Pengadaan" dan "Scope INKA" tidak dianggap sebagai bagian dari nama
    field. Setiap bagian kemudian bisa dicocokkan secara exact terhadap
    KATA_KUNCI.
    """
    if text is None:
        return []

    raw_parts = str(text).split("||")
    return [part.strip() for part in raw_parts if part.strip()]


def similarity_header(text, keyword, field=None):
    """
    Exact matching terhadap KATA_KUNCI dengan dukungan multi-row header.

    Untuk header biasa:
        "Total PR" -> cocok dengan "total pr".

    Untuk multi-row header:
        "Pengadaan || Scope INKA || Total PR" -> tetap cocok dengan
        keyword "total pr" karena pencocokan dilakukan pada setiap bagian
        header, bukan pada gabungan seluruh parent header.

    Tidak menggunakan fuzzy matching, substring, token subset, atau
    SequenceMatcher.
    """
    if not normalize_text(keyword):
        return 0

    key_norm = normalize_text(keyword)
    key_compact = normalize_compact(key_norm)

    for part in _header_parts(text):
        text_norm = normalize_text(part)

        if not text_norm:
            continue

        # Guard untuk memisahkan Kode Material dan Kode Material Delete.
        if field == "kode" and "delete" in text_norm.split():
            continue

        # Guard tambahan untuk mencegah Qty Total (Pre Series) tertukar
        # dengan Qty Total (Series).
        if field == "qty_allowance" and "pre" in text_norm.split():
            continue

        # Exact setelah normalisasi teks.
        if text_norm == key_norm:
            return 100

        # Exact setelah spasi dan tanda baca dihilangkan.
        # Contoh: "Material/Komponen" == "Material / Komponen".
        text_compact = normalize_compact(text_norm)
        if text_compact == key_compact:
            return 98

    return 0


# Threshold per field
# Tetap dipertahankan untuk kompatibilitas; matching sekarang hanya menghasilkan 0, 98, atau 100.
THRESHOLD_FIELD = {
    "kode": 78,
    "kode_delete": 78,
    "stock_total": 70,
    "kode_stock": 78,
    "nama": 72,
    "spek": 72,
    "qty": 72,
    "uom": 75,
    "qty_allowance": 80,  # Ditingkatkan sedikit untuk mencegah false positive pada 'Pre Series'
    "qty_pr_total": 70,
}


# ============================================================
# 7. GABUNGKAN MULTI-ROW HEADER
# ============================================================

def gabungkan_header(data, start_row, jumlah_baris):
    end_row = min(start_row + jumlah_baris, len(data))
    if start_row >= end_row:
        return []

    max_col = max(len(data[row_idx]) for row_idx in range(start_row, end_row))
    hasil = []

    for col_idx in range(max_col):
        values = []
        for row_idx in range(start_row, end_row):
            if col_idx >= len(data[row_idx]):
                continue
            value = str(data[row_idx][col_idx]).strip()
            if not value:
                continue
            if value not in values:
                values.append(value)
        # Simpan setiap level header secara terpisah. Ini penting agar
        # "Pengadaan || Scope INKA || Total PR" tetap bisa menemukan
        # keyword exact "Total PR" tanpa harus memasukkan parent header
        # ke dalam KATA_KUNCI.
        hasil.append(" || ".join(values))

    return hasil


# ============================================================
# 8. MATCHING FIELD KE KOLOM SECARA GLOBAL
# ============================================================

def cari_mapping_header(header_columns):
    kandidat = []

    for col_idx, header_text in enumerate(header_columns):
        if not normalize_text(header_text):
            continue

        for field, keywords in KATA_KUNCI.items():
            best_score = 0
            best_keyword = None

            for keyword in keywords:
                score = similarity_header(header_text, keyword, field=field)
                if score > best_score:
                    best_score = score
                    best_keyword = keyword

            threshold = THRESHOLD_FIELD[field]

            if best_score >= threshold:
                kandidat.append({
                    "field": field,
                    "col_idx": col_idx,
                    "score": best_score,
                    "keyword": best_keyword,
                    "header": header_text
                })

    kandidat.sort(key=lambda x: x["score"], reverse=True)

    mapping = {
        "kode": None, "kode_delete": None, "stock_total": None,
        "kode_stock": None, "nama": None, "spek": None,
        "qty": None, "uom": None, "qty_allowance": None, "qty_pr_total": None
    }

    field_scores = {field: 0 for field in mapping}
    kolom_terpakai = set()

    for item in kandidat:
        field = item["field"]
        col_idx = item["col_idx"]

        if mapping[field] is not None:
            continue
        if col_idx in kolom_terpakai:
            continue

        mapping[field] = col_idx
        field_scores[field] = item["score"]
        kolom_terpakai.add(col_idx)

    return mapping, field_scores, kandidat


# ============================================================
# 9. CARI HEADER TERBAIK
# ============================================================

def deteksi_header(data, max_scan=100, max_header_rows=4):
    kandidat_header = []
    jumlah_baris_scan = min(max_scan, len(data))

    for start_row in range(jumlah_baris_scan):
        for jumlah_baris in range(1, max_header_rows + 1):
            end_row_exclusive = start_row + jumlah_baris
            if end_row_exclusive > len(data):
                continue

            header_columns = gabungkan_header(data, start_row, jumlah_baris)
            mapping, field_scores, kandidat_field = cari_mapping_header(header_columns)

            jumlah_field = sum(1 for value in mapping.values() if value is not None)
            if jumlah_field == 0:
                continue

            first_row_mapping, _, _ = cari_mapping_header(data[start_row])
            jumlah_field_first_row = sum(1 for value in first_row_mapping.values() if value is not None)

            total_score = sum(field_scores.values())
            bonus_identitas = 0

            if mapping["kode"] is not None:
                bonus_identitas += 25
            if mapping["nama"] is not None:
                bonus_identitas += 35

            strong_matches = sum(1 for value in field_scores.values() if value >= 95)
            total_score += bonus_identitas + (strong_matches * 5)

            if mapping["kode"] is None and mapping["nama"] is None:
                continue

            kandidat_header.append({
                "row_idx": start_row,
                "end_row_idx": end_row_exclusive - 1,
                "jumlah_baris": jumlah_baris,
                "mapping": mapping,
                "field_scores": field_scores,
                "score": total_score,
                "jumlah_field": jumlah_field,
                "jumlah_field_first_row": jumlah_field_first_row,
                "header_columns": header_columns,
                "kandidat_field": kandidat_field
            })

    if not kandidat_header:
        return None

    kandidat_header.sort(
        key=lambda x: (
            x["jumlah_field"],
            x["jumlah_field_first_row"],
            x["score"],
            -x["jumlah_baris"]
        ),
        reverse=True
    )

    return kandidat_header[0]


# ============================================================
# 10. DEBUG HEADER
# ============================================================

def tampilkan_debug_header(hasil_header):
    print(f"  Header range: Row {hasil_header['row_idx'] + 1} - {hasil_header['end_row_idx'] + 1}")
    print(f"  Jumlah baris header: {hasil_header['jumlah_baris']}")
    print(f"  Jumlah header terdeteksi: {hasil_header['jumlah_field']}")
    print(f"  Mapping: {hasil_header['mapping']}")
    print("  Detail mapping:")

    for field, col_idx in hasil_header["mapping"].items():
        if col_idx is None:
            print(f"    - {field}: TIDAK TERDETEKSI")
            continue

        score = hasil_header["field_scores"].get(field, 0)
        header_text = hasil_header["header_columns"][col_idx]
        print(f"    - {field}: kolom {col_idx + 1}, score={score}, header='{header_text}'")


# ============================================================
# 11. PARSE ANGKA
# ============================================================

def parse_number(value):
    if value is None:
        return 0.0

    text = str(value).strip()
    if not text:
        return 0.0

    text_upper = text.upper()
    invalid_values = [
        "N/A", "-", "#N/A", "#VALUE!", "#REF!", "#DIV/0!", "#NAME?", "#REF"
    ]

    if text_upper in invalid_values:
        return 0.0

    text = text.replace(",", ".")
    match = re.search(r"-?\d+(?:\.\d+)?", text)

    if not match:
        return 0.0

    try:
        return float(match.group(0))
    except ValueError:
        return 0.0


# ============================================================
# 12. HELPER AMBIL CELL
# ============================================================

def get_cell(row, col_idx, default=""):
    if col_idx is None or col_idx < 0 or col_idx >= len(row):
        return default
    return str(row[col_idx]).strip()


def ambil_kode_wbs(data):
    """
    Mengambil Kode WBS dari baris ke-2 spreadsheet (index 1).

    Prioritas:
    1. Jika ada cell seperti "WBS: ABC-123" / "WBS - ABC-123", ambil ABC-123.
    2. Jika ada cell bernilai "WBS", ambil cell non-kosong berikutnya pada baris yang sama.
    3. Jika tidak ada label WBS, ambil cell non-kosong pertama pada baris ke-2.

    Nilai ini berlaku untuk seluruh data dari satu sheet.
    """
    if len(data) < 2:
        return ""

    row_wbs = data[1]
    values = [str(value).strip() for value in row_wbs if str(value).strip()]

    if not values:
        return ""

    # Kasus: "WBS: ABC-123" / "WBS - ABC-123".
    for value in values:
        match = re.search(r"\bwbs\b\s*[:\-]?\s*(.+)$", value, flags=re.IGNORECASE)
        if match:
            hasil = match.group(1).strip()
            if hasil:
                return hasil

    # Kasus: cell "WBS" berdiri sendiri, lalu kode berada di cell berikutnya.
    for idx, value in enumerate(row_wbs):
        if normalize_text(value) == "wbs":
            for next_value in row_wbs[idx + 1:]:
                next_value = str(next_value).strip()
                if next_value:
                    return next_value

    # Jika row 2 hanya berisi kode WBS tanpa label, ambil nilai non-kosong pertama.
    return values[0]


# ============================================================
# 13. PROSES SEMUA SHEET
# ============================================================

rekap_data = []

for target_name in target_sheets_matched:
    sheet = spreadsheet.worksheet(target_name)
    data_mentah = sheet.get_all_values()

    if not data_mentah:
        print(f"Sheet '{target_name}' -> [SKIP] Tidak ada data.")
        continue

    hasil_header = deteksi_header(data_mentah, max_scan=100, max_header_rows=5)

    if hasil_header is None:
        print(f"Sheet '{target_name}' -> [SKIP] Header tidak ditemukan.")
        continue

    mapping = hasil_header["mapping"]
    kode_wbs = ambil_kode_wbs(data_mentah)

    print(f"\nSheet '{target_name}'")
    print(f"  Kode WBS (Row 2): {kode_wbs or 'TIDAK DITEMUKAN'}")
    tampilkan_debug_header(hasil_header)

    if mapping["kode"] is None and mapping["nama"] is None:
        print("  -> [SKIP] Tidak ada kolom Kode Material atau Material/Komponen.")
        continue

    data_start_idx = hasil_header["end_row_idx"] + 1
    print(f"  Data mulai pada Row {data_start_idx + 1}")

    baris_terproses = 0

    for row in data_mentah[data_start_idx:]:
        kode_material = get_cell(row, mapping["kode"])
        kode_material_delete = get_cell(row, mapping["kode_delete"])
        stock_total = parse_number(get_cell(row, mapping["stock_total"]))
        kode_stock = get_cell(row, mapping["kode_stock"])
        nama_material = get_cell(row, mapping["nama"])
        spesifikasi = get_cell(row, mapping["spek"])
        uom_car = get_cell(row, mapping["uom"])

        valid_qty = parse_number(get_cell(row, mapping["qty"]))
        valid_allowance = parse_number(get_cell(row, mapping["qty_allowance"]))
        valid_pr_total = parse_number(get_cell(row, mapping["qty_pr_total"]))

        kata_abaikan = {
            "kode material", "kode", "total", "subtotal",
            "header", "item code", "part number", "k o d e"
        }

        kode_lower = kode_material.lower().strip()

        if not kode_material and not kode_material_delete:
            continue
        if kode_lower in kata_abaikan:
            continue
        if kode_material_delete.lower().strip() in kata_abaikan:
            continue

        rekap_data.append([
            target_name,
            kode_wbs,
            kode_material,
            kode_material_delete,
            kode_stock,
            stock_total,
            nama_material,
            spesifikasi,
            valid_qty,
            uom_car,
            valid_allowance,
            valid_pr_total
        ])

        baris_terproses += 1

    print(f"  -> {baris_terproses} baris terambil.")


# ============================================================
# 14. DATAFRAME
# ============================================================

df_rekap = pd.DataFrame(
    rekap_data,
    columns=[
        "Nama Sheet Sumber",
        "WBS Elem",
        "Kode Material",
        "Kode Material Delete",
        "Kode Material Stock",
        "Stock Total",
        "Material / Komponen",
        "Spesifikasi",
        "Qty / TS (Series)",
        "UoM/Car",
        "Qty Total (Series) + Allowance",
        "QTY PR TOTAL"
    ]
)


# ============================================================
# 15. RINGKASAN
# ============================================================

print("\n--- RINGKASAN HASIL PER SHEET ---")

if not df_rekap.empty:
    print(df_rekap.groupby("Nama Sheet Sumber").size())
else:
    print("Tidak ada data yang berhasil diambil.")


# ============================================================
# 16. TULIS KE GOOGLE SHEETS
# ============================================================

nama_tab_rekap = "REKAP_BOM_TOTAL (Berdasarkan Kode Material) 2"

try:
    sheet_rekap = spreadsheet.worksheet(nama_tab_rekap)
    sheet_rekap.clear()
except gspread.exceptions.WorksheetNotFound:
    sheet_rekap = spreadsheet.add_worksheet(
        title=nama_tab_rekap,
        rows="8000",
        cols="12"
    )

data_ke_sheets = (
    [df_rekap.columns.values.tolist()]
    + df_rekap.values.tolist()
)

sheet_rekap.update(data_ke_sheets)

print(
    f"\n[SUKSES] TOTAL {len(df_rekap)} baris data berhasil "
    f"ditarik dan disimpan ke sheet '{nama_tab_rekap}'."
)

[INFO] Memetakan 29 dari 29 target sheet.


Sheet 'Elektrik + Pre Series'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 385 baris terambil.

Sheet 'De-Scoping'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 5 - 7
  Jumlah baris header: 3
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 37, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 36, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 38, score=100, header='Pengadaan || Scope INKA || Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 37, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series) || + Allowance'
    - qty_pr_total: kolom 45, score=100, header='Total PR'
  Data mulai pada Row 8
  -> 768 baris terambil.

Sheet 'Interior'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material/Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 435 baris terambil.

Sheet 'TMS'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 28 baris terambil.

Sheet 'CKD VVVF'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 185 baris terambil.

Sheet 'CKD Pantograph'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 394 baris terambil.

Sheet 'CKD SIV'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 160 baris terambil.

Sheet 'Elektrik'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 465 baris terambil.

Sheet 'Komponen Utama'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 179 baris terambil.

Sheet 'Sistem Mekanik'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 5 - 6
  Jumlah baris header: 2
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 532 baris terambil.

Sheet 'Raw Material Interior'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='SPESIFIKASI'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 82 baris terambil.

Sheet 'Bogie KIT'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Bogie'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 44 baris terambil.

Sheet 'Raw Material Bogie'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 6, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 7, score=100, header='Kode Material Stock 1'
    - nama: kolom 13, score=100, header='Deskripsi Material'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 99 baris terambil.

Sheet 'Realisasi Raw Material'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 4 - 5
  Jumlah baris header: 2
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 7, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material Asli'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 8, score=100, header='Kode Material Stock 2'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 6
  -> 123 baris terambil.

Sheet 'Carbody'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material/Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 268 baris terambil.

Sheet 'Fastening Mekanik'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=98, header='KodeMaterial'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UoM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='Total PR'
  Data mulai pada Row 7
  -> 984 baris terambil.

Sheet 'Fastening Bogie'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=98, header='KodeMaterial'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 123 baris terambil.

Sheet 'Fastening Interior'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=98, header='KodeMaterial'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 562 baris terambil.

Sheet 'Crashwrothiness'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series)'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 19 baris terambil.

Sheet 'Welding'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 5 - 6
  Jumlah baris header: 2
  Jumlah header terdeteksi: 10
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': 30, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'
    - kode_delete: kolom 12, score=100, header='Kode Material Delete'
    - stock_total: kolom 37, score=100, header='Stock Total'
    - kode_stock: kolom 6, score=100, header='Kode Material Stock'
    - nama: kolom 13, score=100, header='Material / Komponen'
    - spek: kolom 14, score=100, header='Spesifikasi'
    - qty: kolom 31, score=100, header='Qty/TS (Series)'
    - uom: kolom 36, score=100, header='UOM/Car'
    - qty_allowance: kolom 35, score=100, header='Qty Total (Series) + Allowance'
    - qty_pr_total: kolom 45, score=100, header='QTY PR TOTAL'
  Data mulai pada Row 7
  -> 118 baris terambil.

Sheet 'Welding Bogie'
  Kode WBS (Row 2): S-22002.1
  Header range: Row 6 - 6
  Jumlah baris header: 1
  Jumlah header terdeteksi: 9
  Mapping: {'kode': 4, 'kode_delete': 11, 'stock_total': 36, 'kode_stock': 5, 'nama': 12, 'spek': 13, 'qty': None, 'uom': 35, 'qty_allowance': 34, 'qty_pr_total': 44}
  Detail mapping:
    - kode: kolom 5, score=100, header='Kode Material'

# Read Data

In [12]:
bom_data_url = "https://docs.google.com/spreadsheets/d/1Ibki18gicAFziEx1urTrvDv_KkzrkMMnRrbwqNYpOkw/export?format=csv&gid=386174298"
bom_data = pd.read_csv(bom_data_url, low_memory=False)

sap_data_url = "https://docs.google.com/spreadsheets/d/1jnuEazMkGxbXcvP2mvvGlRZQZR-N0FMPf3aNhw5lH7Q/export?format=csv&gid=826586568"
sap_data = pd.read_csv(sap_data_url, low_memory=False)
sap_dataset = pd.read_csv(sap_data_url, low_memory=False)

In [13]:
len(bom_data)

7937

In [14]:
len(sap_data)

108300

In [15]:
total_duplicated_bom_data = bom_data.duplicated().sum()
print(f"Jumlah baris duplikat: {total_duplicated_bom_data}")

Jumlah baris duplikat: 394

In [16]:
total_duplicated_sap_data = sap_data.duplicated().sum()
print(f"Jumlah baris duplikat: {total_duplicated_sap_data}")

Jumlah baris duplikat: 4

In [17]:
sap_data.drop_duplicates(inplace=True)

In [18]:
bom_data.drop_duplicates(inplace=True)

In [19]:
bom_data.columns = bom_data.columns.str.strip()

sap_data.columns = sap_data.columns.str.strip()
sap_dataset.columns = sap_dataset.columns.str.strip()

sap_data['Qty Requested'] = pd.to_numeric(sap_data['Qty Requested'].str.replace(',', '').str.replace('.', ''), errors='coerce')
sap_data['Qty Requested'] = sap_data['Qty Requested'].fillna(0).astype(int)
sap_data['Ordered'] = pd.to_numeric(sap_data['Ordered'].str.replace(',', '').str.replace('.', ''), errors='coerce')
sap_data['Ordered'] = sap_data['Ordered'].fillna(0).astype(int)

In [20]:
filtered_bom_data = bom_data[bom_data["Kode Material Delete"].isna()]

In [21]:
# filtered_bom_data = filtered_bom_data.groupby("Kode Material", as_index=False).agg({
#     'Nama Sheet Sumber': lambda x: ', '.join(x.unique()),
#     'WBS Elem': 'first',
#     'Material / Komponen': 'first',
#     'Kode Material Delete': lambda x: ', '.join(x.dropna().astype(str).unique()),
#     'Kode Material Stock': 'first',
#     'Stock Total': 'sum',
#     'Qty / TS (Series)': 'sum',
#     'UoM/Car': 'first',
#     'Qty Total (Series) + Allowance': 'sum',
#     'Spesifikasi': 'first',
#     'QTY PR TOTAL': 'sum'
# })

In [40]:
len(filtered_bom_data)

6409

In [23]:
# result = (
#     sap_data.groupby("Kode Material")["WBS Description"]
#     .nunique()
#     .reset_index(name="Jumlah_WBS")
# )
# result.head()

In [41]:
sap_data["WBS Elem"].head(10)

0    B-18001.1
1    B-18001.1
2    B-18001.1
3    B-18001.1
4    B-18001.1
5    B-18001.1
6    B-18001.1
7    B-18001.1
8    B-18001.1
9    B-18001.1
Name: WBS Elem, dtype: object

In [25]:
sap_data["WBS_Group"] = sap_data["WBS Elem"].str.extract(
    r"^([A-Z]-\d+\.\d+)"
)

In [26]:
filtered_sap_data = sap_data.groupby(['Kode Material', 'WBS_Group'], as_index=False).agg({
    'WBS Description': 'first',
    'Mat. Description': 'first',
    'Spesifikasi': 'first',
    'PR Status': 'first',
    'Qty Requested': 'sum',
    'Ordered': 'sum'
})

In [27]:
filtered_sap_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15326 entries, 0 to 15325
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Kode Material     15326 non-null  object
 1   WBS_Group         15326 non-null  object
 2   WBS Description   15326 non-null  object
 3   Mat. Description  15326 non-null  object
 4   Spesifikasi       15088 non-null  object
 5   PR Status         15326 non-null  object
 6   Qty Requested     15326 non-null  int64
 7   Ordered           15326 non-null  int64
dtypes: int64(2), object(6)
memory usage: 958.0+ KB

In [28]:
filtered_bom_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6409 entries, 8 to 7936
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Nama Sheet Sumber               6409 non-null   object
 1   WBS Elem                        6409 non-null   object
 2   Kode Material                   6409 non-null   object
 3   Kode Material Delete            0 non-null      object
 4   Kode Material Stock             552 non-null    object
 5   Stock Total                     6409 non-null   float64
 6   Material / Komponen             6399 non-null   object
 7   Spesifikasi                     6168 non-null   object
 8   Qty / TS (Series)               6409 non-null   float64
 9   UoM/Car                         5805 non-null   object
 10  Qty Total (Series) + Allowance  6409 non-null   float64
 11  QTY PR TOTAL                    6409 non-null   float64
dtypes: float64(4), object(8)
memory usage: 909.0+ KB

In [29]:
len(filtered_sap_data[filtered_sap_data["WBS_Group"].str.contains("S-22002.1", regex=False, na=False)])

4185

In [30]:
sap_data[(sap_data["Kode Material"] == "B336E12003") & (sap_data["WBS_Group"].str.contains("S-22002.1", regex=False, na=False))][["WBS_Group", "WBS Description", "Kode Material", "Qty Requested", "Ordered"]]

,WBS_Group,WBS Description,Kode Material,Qty Requested,Ordered
12572,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),B336E12003,24,24
17472,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),B336E12003,24,24
17473,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),B336E12003,24,24
17474,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),B336E12003,24,24
17734,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M2),B336E12003,24,24
17735,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M2),B336E12003,24,24
17736,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M2),B336E12003,24,24
17737,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M2),B336E12003,24,24

In [31]:
filtered_sap_data[filtered_sap_data["Kode Material"] == "B336E12003"]
# yang WBS Elemnya mengandung 'S-22002.1',

,Kode Material,WBS_Group,WBS Description,Mat. Description,Spesifikasi,PR Status,Qty Requested,Ordered
5979,B336E12003,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),TMJB,Refer to dwg. 33.2-E12004 <(>&<)> 86.2-E12003...,B,192,192
5980,B336E12003,S-23001.1,RETROFIT 2 TS KRL KCI (6 M1),TMJB,Refer to dwg. 33.2-E12004 <(>&<)> 86.2-E12003...,B,24,24

In [32]:
merge_data = pd.merge(
    filtered_bom_data,
    filtered_sap_data,
    left_on=['Kode Material', 'WBS Elem'],
    right_on=['Kode Material', 'WBS_Group'],
    how='inner'
)

In [33]:
merge_data

,Nama Sheet Sumber,WBS Elem,Kode Material,Kode Material Delete,Kode Material Stock,Stock Total,Material / Komponen,Spesifikasi_x,Qty / TS (Series),UoM/Car,Qty Total (Series) + Allowance,QTY PR TOTAL,WBS_Group,WBS Description,Mat. Description,Spesifikasi_y,PR Status,Qty Requested,Ordered
0,Elektrik + Pre Series,S-22002.1,B336E12003,NaN,NaN,0.0,TMJB,Refer to dwg. 33.6-E12003 33.2-E12004 & 86.2-E...,12.0,set,192.0,192.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),TMJB,Refer to dwg. 33.2-E12004 <(>&<)> 86.2-E12003...,B,192,192
1,Elektrik + Pre Series,S-22002.1,B680E12101,NaN,NaN,0.0,Partition Control Panel A TC1&TC2,"Refer to dwg. 68.0-E12101 & 86.2-E12104, 59.4-...",2.0,set,32.0,32.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Partition Control Panel A TC1&TC2,Refer to dwg. 68.0-E12101 <(>&<)> 86.2-E12104...,B,32,32
2,Elektrik + Pre Series,S-22002.1,B680E12102,NaN,NaN,0.0,Partition Control Panel B TC1&TC2,"Refer to dwg. 68.0-E12102 & 86.2-E12105, 59.4-...",2.0,set,32.0,32.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Partition Control Panel B TC1&TC2,Refer to dwg. 68.0-E12102 <(>&<)> 86.2-E12105...,B,32,32
3,Elektrik + Pre Series,S-22002.1,B490E12101,NaN,NaN,0.0,Endwall Control Panel A TC1&TC2,"Refer to dwg. 49.0-E12101 & 86.2-E12102, 59.4-...",2.0,set,32.0,32.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Endwall Control Panel A TC1&TC2,Refer to dwg. 49.0-E12101 <(>&<)> 86.2-E12102...,B,32,32
4,Elektrik + Pre Series,S-22002.1,B490E12102,NaN,NaN,0.0,Endwall Control Panel B TC1&TC2,"Refer to dwg. 49.0-E12102 & 86.2-E12103, 59.4-...",2.0,set,32.0,32.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Endwall Control Panel B TC1&TC2,Refer to dwg. 49.0-E12102 <(>&<)> 86.2-E12103...,B,32,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5835,Consumable Pre Series,S-22002.1,D50EB651032AX#RD,NaN,NaN,0.0,STICKER ORACAL RED,UK 1260 X 50000mm (651G-032),0.0,Roll,0.0,0.0,S-22002.1,PENGADAAN 16 TS KRL KCI,STICKER ORACAL LIGHT RED,UK 1260 X 50000mm (651G-032),B,150,82
5836,Consumable Pre Series,S-22002.1,D68QH0713577,NaN,NaN,0.0,PIPE SEALANT,MXLOC 13577 PIPE SEALANT,0.0,mL,0.0,100.0,S-22002.1,PENGADAAN 16 TS KRL KCI,PIPE SEALANT,MXLOC 13577 (1Pc=50mL),B,4900,4900
5837,Consumable Pre Series,S-22002.1,D68QH0700577,NaN,NaN,0.0,TRHEAD LOCKER,MXLOC 577 THREAD LOCKER ADHESIVE,0.0,mL,0.0,100.0,S-22002.1,PENGADAAN 16 TS KRL KCI,THREAD LOCKER ADHESHIVE,MXLOC 577 (1Pc=50Ml),B,4900,4900
5838,Consumable Pre Series,S-22002.1,D68QH0002,NaN,NaN,0.0,PLASEAL B-UF,NFPA 130/ EN 45545-2,0.0,kg,0.0,10.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),Plaseal B-UF,NFPA 130/ EN 45545-2,B,1442,1442
5839,Consumable Pre Series,S-22002.1,D68WH0837,NaN,NaN,0.0,DIELECTRIC GREASE,SILICONE COMPOUND,0.0,gr,0.0,200.0,S-22002.1,PENGADAAN 16 TS KRL KCI,Dielectric Grease,Silicone Compound,B,200,200

In [34]:
stockData = merge_data[(merge_data["Kode Material Stock"].isna() & (merge_data["Stock Total"] > 0.0)) | (merge_data["Kode Material Stock"].notna() & ((merge_data['Stock Total'] > 0.0) | (merge_data['Stock Total'] == 0.0)))]
otherData = merge_data[merge_data['Kode Material Stock'].isna() & (merge_data['Stock Total'] == 0.0)]
belumPRData = otherData[(otherData["QTY PR TOTAL"] > otherData["Qty Requested"])]
sudahPRData = otherData[otherData["QTY PR TOTAL"] == otherData["Qty Requested"]]
partialPRData = otherData[otherData["QTY PR TOTAL"] < otherData["Qty Requested"]]

In [35]:
data = {
    'Status': ['Belum PR', 'Sudah PR', 'Stock', 'Partial PR'],
    'Jumlah': [len(belumPRData), len(sudahPRData), len(stockData), len(partialPRData)]
}
df = pd.DataFrame(data)
fig = px.pie(
    df,
    names='Status',
    values='Jumlah',
    title='Persentase Distribusi Material',
    hole=0.3
)

# 3. Menampilkan grafik
fig.show()

In [91]:
merge_data[merge_data["Kode Material Stock"].isna()]

,Nama Sheet Sumber,WBS Elem,Kode Material,Kode Material Delete,Kode Material Stock,Stock Total,Material / Komponen,Spesifikasi_x,Qty / TS (Series),UoM/Car,Qty Total (Series) + Allowance,QTY PR TOTAL,WBS_Group,WBS Description,Mat. Description,Spesifikasi_y,PR Status,Qty Requested,Ordered
0,Elektrik + Pre Series,S-22002.1,B336E12003,NaN,NaN,0.0,TMJB,Refer to dwg. 33.6-E12003 33.2-E12004 & 86.2-E...,12.0,set,192.0,192.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),TMJB,Refer to dwg. 33.2-E12004 <(>&<)> 86.2-E12003...,B,192,192
1,Elektrik + Pre Series,S-22002.1,B680E12101,NaN,NaN,0.0,Partition Control Panel A TC1&TC2,"Refer to dwg. 68.0-E12101 & 86.2-E12104, 59.4-...",2.0,set,32.0,32.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Partition Control Panel A TC1&TC2,Refer to dwg. 68.0-E12101 <(>&<)> 86.2-E12104...,B,32,32
2,Elektrik + Pre Series,S-22002.1,B680E12102,NaN,NaN,0.0,Partition Control Panel B TC1&TC2,"Refer to dwg. 68.0-E12102 & 86.2-E12105, 59.4-...",2.0,set,32.0,32.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Partition Control Panel B TC1&TC2,Refer to dwg. 68.0-E12102 <(>&<)> 86.2-E12105...,B,32,32
3,Elektrik + Pre Series,S-22002.1,B490E12101,NaN,NaN,0.0,Endwall Control Panel A TC1&TC2,"Refer to dwg. 49.0-E12101 & 86.2-E12102, 59.4-...",2.0,set,32.0,32.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Endwall Control Panel A TC1&TC2,Refer to dwg. 49.0-E12101 <(>&<)> 86.2-E12102...,B,32,32
4,Elektrik + Pre Series,S-22002.1,B490E12102,NaN,NaN,0.0,Endwall Control Panel B TC1&TC2,"Refer to dwg. 49.0-E12102 & 86.2-E12103, 59.4-...",2.0,set,32.0,32.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Endwall Control Panel B TC1&TC2,Refer to dwg. 49.0-E12102 <(>&<)> 86.2-E12103...,B,32,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5835,Consumable Pre Series,S-22002.1,D50EB651032AX#RD,NaN,NaN,0.0,STICKER ORACAL RED,UK 1260 X 50000mm (651G-032),0.0,Roll,0.0,0.0,S-22002.1,PENGADAAN 16 TS KRL KCI,STICKER ORACAL LIGHT RED,UK 1260 X 50000mm (651G-032),B,150,82
5836,Consumable Pre Series,S-22002.1,D68QH0713577,NaN,NaN,0.0,PIPE SEALANT,MXLOC 13577 PIPE SEALANT,0.0,mL,0.0,100.0,S-22002.1,PENGADAAN 16 TS KRL KCI,PIPE SEALANT,MXLOC 13577 (1Pc=50mL),B,4900,4900
5837,Consumable Pre Series,S-22002.1,D68QH0700577,NaN,NaN,0.0,TRHEAD LOCKER,MXLOC 577 THREAD LOCKER ADHESIVE,0.0,mL,0.0,100.0,S-22002.1,PENGADAAN 16 TS KRL KCI,THREAD LOCKER ADHESHIVE,MXLOC 577 (1Pc=50Ml),B,4900,4900
5838,Consumable Pre Series,S-22002.1,D68QH0002,NaN,NaN,0.0,PLASEAL B-UF,NFPA 130/ EN 45545-2,0.0,kg,0.0,10.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),Plaseal B-UF,NFPA 130/ EN 45545-2,B,1442,1442
5839,Consumable Pre Series,S-22002.1,D68WH0837,NaN,NaN,0.0,DIELECTRIC GREASE,SILICONE COMPOUND,0.0,gr,0.0,200.0,S-22002.1,PENGADAAN 16 TS KRL KCI,Dielectric Grease,Silicone Compound,B,200,200

In [163]:
partialPRData.head(20)

,Nama Sheet Sumber,WBS Elem,Kode Material,Kode Material Delete,Kode Material Stock,Stock Total,Material / Komponen,Spesifikasi_x,Qty / TS (Series),UoM/Car,Qty Total (Series) + Allowance,QTY PR TOTAL,WBS_Group,WBS Description,Mat. Description,Spesifikasi_y,PR Status,Qty Requested,Ordered
23,Elektrik + Pre Series,S-22002.1,B52TI2203,NaN,NaN,0.0,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",6.0,Pcs,96.0,96.0,S-22002.1,PENGADAAN 16 TS KRL KCI,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",B,129,129
26,Elektrik + Pre Series,S-22002.1,B52TI0178,NaN,NaN,0.0,Push Button Protector Cover,"PUSH BUTTON PROTECTOR COVER, APT F38-30B",2.0,Pcs,32.0,32.0,S-22002.1,PENGADAAN 16 TS KRL KCI,Push Button Protector Cover,"PUSH BUTTON PROTECTOR COVER, APT F38-30B",B,96,96
29,Elektrik + Pre Series,S-22002.1,B52TE6111,NaN,NaN,0.0,Fog Lamp,"GE LIGHTING PAR 56, 20849 – 300PAR56/NSP-120V",4.0,Pcs,64.0,64.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Fog lamp,"GE LIGHTING PAR 56, 20849 – 300PAR56/NSP-120V",B,66,66
30,Elektrik + Pre Series,S-22002.1,B52TE6346,NaN,NaN,0.0,Head Signal Light Red/Door Open Lamp,"APT, AD16-60KTKA-r, Red, 110 VDC",4.0,Pcs,64.0,64.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Head Signal Light Red,"APT, AD16-60KTKA-r, Red, 110 VDC",B,444,444
31,Elektrik + Pre Series,S-22002.1,B52TE6336,NaN,NaN,0.0,Head Signal Light White/Propultion Lamp,"APT, AD16-60KTKA-w, White, 110 VDC",4.0,Pcs,64.0,64.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Front Signal Lamp White,"APT, AD16-60KTKA-w, White, 110 VDC",B,256,256
33,Elektrik + Pre Series,S-22002.1,B52TE015,NaN,NaN,0.0,Cabin Lamp,"Lumino, PLD009WDC, 110 VDC, 9W, LED Downlight,...",4.0,Pcs,64.0,64.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Cabin Lamp,"Lumino, PLD009WDC, 110 VDC, 9W, LED Downlight...",B,65,65
35,Elektrik + Pre Series,S-22002.1,B52TE6336,NaN,NaN,0.0,Propultion Lamp/Head Signal Light White,"APT, AD16-60KTKA-w, White, 110 VDC",12.0,Pcs,192.0,192.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Front Signal Lamp White,"APT, AD16-60KTKA-w, White, 110 VDC",B,256,256
36,Elektrik + Pre Series,S-22002.1,B52TE3445,NaN,NaN,0.0,Emergency Lighting,"LED Tube PC Cover, Double End Power, PANASONIC...",48.0,Pcs,768.0,768.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Emergency Lighting,"LED Tube PC Cover, Double End Power, PANASONI...",B,776,776
37,Elektrik + Pre Series,S-22002.1,B52TE3446,NaN,NaN,0.0,Room Lighting,"LED Tube PC Cover, Double End Power, PANASONIC...",280.0,Pcs,4480.0,4480.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Room Lighting,"LED Tube PC Cover, Double End Power, PANASONI...",B,4530,4530
38,Elektrik + Pre Series,S-22002.1,B52TI1256,NaN,NaN,0.0,Housing Head Lamp,"Housing for Bulb type PAR56, spring locking, i...",4.0,NaN,64.0,64.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Housing Head Lamp,"Housing for Bulb type PAR56, spring locking,...",B,128,128
42,Elektrik + Pre Series,S-22002.1,A52ZG41500,NaN,NaN,0.0,Main Circuit Cable,"150 mmSQ , 3600V, SpekTek: 307-SPT-K1003TB091-16",1056.0,meter,17234.0,17500.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),Main Circuit Cable,"150 mmsq, 3600V, SpekTek: 307-SPT-K1003TB091-16",B,1354000,1354000
44,Elektrik + Pre Series,S-22002.1,A52ZG40710,NaN,NaN,0.0,Main Circuit Cable,"70 mmSQ , 3600V, SpekTek: 307-SPT-K1003TB091-16",486.0,meter,7932.0,7932.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),Main Circuit Cable,"70 mmSQ , 3600V, SpekTek: 307-SPT-K1003TB091-16",B,399972,399972
46,Elektrik + Pre Series,S-22002.1,A52YC1070,NaN,NaN,0.0,Main Circuit Cable,"Rev 0: LEONI/LS/HubSuhner/LAPP, 70 mmsq, shiel...",330.0,meter,5386.0,6000.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),Main Circuit Cable,"LEONI/LS/HubSuhner/LAPP, 70 mmsq, shielded, 1...",B,600000,480480
47,Elektrik + Pre Series,S-22002.1,A52YC2262,NaN,NaN,0.0,Traction Motor Cables,"35 mmSQ Shielded, 1800V, SpekTek: 307-SPT-K100...",282.0,meter,4603.0,4600.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M2),Traction Motor Cables,"35 mmSQ Shielded, 1800V, SpekTek: 307-SPT-K1...",B,138250,138250
48,Elektrik + Pre Series,S-22002.1,A52YC2263,NaN,NaN,0.0,Traction Motor Cables,"16 mmSQ Shielded, 1800V, SpekTek: 307-SPT-K100...",255.0,meter,4203.0,4200.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),Traction Motor Cables,"16 mmSQ Shielded, 1800V, SpekTek: 307-SPT-K10...",B,4320,4320
50,Elektrik + Pre Series,S-22002.1,A52YC1006,NaN,NaN,0.0,Main Circuit Cable,"95mmSQ , 600V, SpekTek: 307/SPT/K1003TB091/16",1393.0,meter,22734.0,22813.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),Main Circuit Cable,"95mmSQ , 600V, SpekTek: 307/SPT/K1003TB091/16",B,1085479,1085479
56,Elektrik + Pre Series,S-22002.1,A52ZG40041,NaN,NaN,0.0,Main Circuit Cable,"4 mmSQ , 3600V, SpekTek: 307-SPTK1003TB091-16",279.0,meter,4554.0,4554.0,S-22002.1,PENGADAAN 16 TS KRL KCI (48 M1),Main Circuit Cable,"4 mmSQ , 3600V, SpekTek: 307-SPT-K1003TB091-16",B,5554,5554
58,Elektrik + Pre Series,S-22002.1,A52YA4012,NaN,NaN,0.0,RS485 Cable,"Multicore Cable 2x2x0.5 mm², 300V, Shielded Tw...",833.0,meter,13595.0,13690.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),RS485 Cable,"Multicore Cable 2x2x0.5 mmÂ², 300V, Shielded ...",B,317719,317719
64,Elektrik + Pre Series,S-22002.1,B52TP1918,NaN,NaN,0.0,Isolator Board and Busbar 4,Refer to dwg. 33.6-E12007,48.0,Pcs,768.0,768.0,S-22002.1,PENGADAAN 16 TS KRL KCI (16 TC1),ISOLATOR BOARD AND BUSBAR 4,REFFER TO DWG. 33.6-E12007,B,772,772
77,Elektrik + Pre Series,S-22002.1,B52TI4005,NaN,NaN,0.0,M12 4 Pin D Coded Male,M12 4 Pin D Coded Male,24.0,pcs,384.0,384.0,S-22002.1,PENGADAAN 16 TS KRL KCI,M12 4 Pin D coded Male,M12 4 pin D coded Male,B,3174,3174

In [172]:
# B52TP3212
# B52TI2203
# B52TE6336
# D68QH0700577

komat = "B52TI2203"

## Check kode material di BOM, SAP, dan Gabungan

In [176]:
filtered_sap_data[filtered_sap_data["Kode Material"] == komat][["WBS_Group", "WBS Description", "Kode Material", "Qty Requested", "Ordered"]]

,WBS_Group,WBS Description,Kode Material,Qty Requested,Ordered
9613,B-18001.1,PENGADAAN SARANA 186 CAR LRT JABODEBEK,B52TI2203,400,400
9614,S-22002.1,PENGADAAN 16 TS KRL KCI,B52TI2203,129,129

In [174]:
filtered_bom_data[filtered_bom_data["Kode Material"] == komat]

,Nama Sheet Sumber,WBS Elem,Kode Material,Kode Material Delete,Kode Material Stock,Stock Total,Material / Komponen,Spesifikasi,Qty / TS (Series),UoM/Car,Qty Total (Series) + Allowance,QTY PR TOTAL
41,Elektrik + Pre Series,S-22002.1,B52TI2203,NaN,NaN,0.0,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",6.0,Pcs,96.0,96.0
2396,Elektrik,S-22002.1,B52TI2203,NaN,NaN,0.0,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",6.0,Pcs,96.0,96.0
2991,Komponen Utama,S-22002.1,B52TI2203,NaN,NaN,0.0,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",2.0,NaN,32.0,33.0

In [175]:
merge_data[merge_data["Kode Material"] == komat]

,Nama Sheet Sumber,WBS Elem,Kode Material,Kode Material Delete,Kode Material Stock,Stock Total,Material / Komponen,Spesifikasi_x,Qty / TS (Series),UoM/Car,Qty Total (Series) + Allowance,QTY PR TOTAL,WBS_Group,WBS Description,Mat. Description,Spesifikasi_y,PR Status,Qty Requested,Ordered
23,Elektrik + Pre Series,S-22002.1,B52TI2203,NaN,NaN,0.0,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",6.0,Pcs,96.0,96.0,S-22002.1,PENGADAAN 16 TS KRL KCI,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",B,129,129
1780,Elektrik,S-22002.1,B52TI2203,NaN,NaN,0.0,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",6.0,Pcs,96.0,96.0,S-22002.1,PENGADAAN 16 TS KRL KCI,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",B,129,129
2162,Komponen Utama,S-22002.1,B52TI2203,NaN,NaN,0.0,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",2.0,NaN,32.0,33.0,S-22002.1,PENGADAAN 16 TS KRL KCI,X-COM Male Connector,"Wago, X-COM Male Plugs 769-605",B,129,129